# Generated by Django 3.2.3 on 2021-06-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('carte_membre', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('top', models.IntegerField(default=0)),
                ('right', models.IntegerField(default=0)),
                ('bottom', models.IntegerField(default=0)),
                ('left', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='detection_client.client')),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='detection_client.etat')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='detection_client.photo')),
            ],
        ),
    ]
