# Generated by Django 3.2.3 on 2021-06-29 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detection_client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiqueclient',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='photo',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
