# Generated by Django 3.2.3 on 2021-06-29 14:42

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('detection_client', '0002_auto_20210629_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=versatileimagefield.fields.VersatileImageField(upload_to='detection_client/uploads/', verbose_name='Image'),
        ),
    ]
