# Generated by Django 3.2.3 on 2021-06-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_client', '0003_auto_20210629_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='carte_membre',
            field=models.IntegerField(default=0),
        ),
    ]
