# Generated by Django 3.2.3 on 2021-06-30 14:02

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('detection_client', '0006_auto_20210630_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueclient',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
