# Generated by Django 3.2.3 on 2021-07-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection_client', '0008_auto_20210701_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueclient',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='detection_client.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiqueclient',
            name='photo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='detection_client.photo'),
            preserve_default=False,
        ),
    ]
