# Generated by Django 3.2.3 on 2021-07-26 10:11

import detection_client.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('detection_client', '0009_auto_20210701_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueclient',
            name='face',
            field=versatileimagefield.fields.VersatileImageField(upload_to=detection_client.models.get_upload_path, verbose_name='Image'),
        ),
    ]
